FInished implementing functionality for the energy detector cover
GTNewHorizons/KekzTech pull request #14
Opened 2021-05-10 23:23 UTC by MatthewCOwen

![image](https://user-images.githubusercontent.com/16054364/117736218-faca0680-b1ab-11eb-9256-8b95471cde7f.png)
these options now work

2021-05-11 07:45 UTC, Glease commented on src/main/java/common/tileentities/GTMTE_LapotronicSuperCapacitor.java
> +				mMaxEUOut = Math.max(mMaxEUOut, tDynamo.maxEUOutput());
Are you sure these variables should all use `max` instead of `+`?

2021-05-11 10:32 UTC, matt-159 commented on src/main/java/common/tileentities/GTMTE_LapotronicSuperCapacitor.java
> +				mMaxEUOut = Math.max(mMaxEUOut, tDynamo.maxEUOutput());
https://github.com/GTNewHorizons/KekzTech/blob/a1a1f04fb64612a1ce1aea7c337bcf67bd9d1361/src/main/java/common/tileentities/GTMTE_LapotronicSuperCapacitor.java#L477-L481
https://github.com/GTNewHorizons/KekzTech/blob/a1a1f04fb64612a1ce1aea7c337bcf67bd9d1361/src/main/java/common/tileentities/GTMTE_LapotronicSuperCapacitor.java#L489-L493
https://github.com/GTNewHorizons/KekzTech/blob/a1a1f04fb64612a1ce1aea7c337bcf67bd9d1361/src/main/java/common/tileentities/GTMTE_LapotronicSuperCapacitor.java#L501-L505
https://github.com/GTNewHorizons/KekzTech/blob/a1a1f04fb64612a1ce1aea7c337bcf67bd9d1361/src/main/java/common/tileentities/GTMTE_LapotronicSuperCapacitor.java#L513-L517
https://github.com/GTNewHorizons/KekzTech/blob/a1a1f04fb64612a1ce1aea7c337bcf67bd9d1361/src/main/java/common/tileentities/GTMTE_LapotronicSuperCapacitor.java#L525-L530
https://github.com/GTNewHorizons/KekzTech/blob/a1a1f04fb64612a1ce1aea7c337bcf67bd9d1361/src/main/java/common/tileentities/GTMTE_LapotronicSuperCapacitor.java#L538-L543

As you can see, the LSC will try to push/pull EU in sizes of  `hatch.maxEUInput() * hatch.maxAmperesIn` or `hatch.maxEUOutput() * hatch.maxAmperesOut`, which is why I chose to use  `max` instead of `+`.

2021-05-11 13:20 UTC, Glease commented on src/main/java/common/tileentities/GTMTE_LapotronicSuperCapacitor.java
> +				mMaxEUOut = Math.max(mMaxEUOut, tDynamo.maxEUOutput());
Yes, but doesn't it do it for all hatches instead of just one of them?

2021-05-11 14:27 UTC, botn365 commented on src/main/java/common/tileentities/GTMTE_LapotronicSuperCapacitor.java
> +		ll.add("EU OUT: " + NumberFormat.getNumberInstance().format(tBMTE.getAverageElectricOutput()) + "EU/t");
dont change this

2021-05-11 15:41 UTC, matt-159 commented on src/main/java/common/tileentities/GTMTE_LapotronicSuperCapacitor.java
> +		ll.add("EU OUT: " + NumberFormat.getNumberInstance().format(tBMTE.getAverageElectricOutput()) + "EU/t");
I'll put it back.

2021-05-11 15:46 UTC, matt-159 commented on src/main/java/common/tileentities/GTMTE_LapotronicSuperCapacitor.java
> +				mMaxEUOut = Math.max(mMaxEUOut, tDynamo.maxEUOutput());
Honestly now that I have thought about it some more, neither appear to be good solutions since you can mix and match dynamo/hatch tiers. 
https://github.com/GTNewHorizons/GT5-Unofficial/blob/a2761733aaad5e1a9368a25b565846fa8ccb6d4b/src/main/java/gregtech/common/covers/GT_Cover_EUMeter.java#L46-L59
The problem lies in this spot I think.
If the total EU/t and Amperage is added up across all hatches and dynamos, then you could have say 4 LV energy hatches + 1  IV energy hatch and adding up EU/t in and Amperes in would make that Energy Detector Cover see 16640eu/t @ 10A
If the total EU/t and Amperage is maxed across all hatches and dynamos, then the Energy Detector Cover would see 8192eu/t @ 2A

2021-05-11 18:25 UTC, bartimaeusnek requested changes
Outcommented code needs to be removed, `addEnergyInputToMachineList` should be split into several smaller (30 Lines max) methodes, the long values _may be better as BigInts_ depending on whether or not the input EU/t exceeds the long capacity, but that's just a theorethical thing. So:

- [x] Outcommented code 

- [x] addEnergyInputToMachineList splitup

2021-05-12 02:56 UTC, bartimaeusnek approved these changes

2021-05-12 06:41 UTC, merged