fix voiding and made fluid pos static
GTNewHorizons/KekzTech pull request #3
Opened 2020-10-11 00:39 UTC by botn365

will fix keztech tank voiding fluids and make the index of a fluid static

2020-10-11 15:17 UTC, glowredman approved these changes
Looks good, as far as I can tell. If it actually works must be checked e.g. on Zeta of course.

2020-10-12 02:22 UTC, Glease requested changes

2020-10-12 02:22 UTC, Glease commented on src/main/java/kekztech/MultiFluidHandler.java
> +				empty = getNullSlot();
No state was modified. No need to compute again.

2020-10-12 14:29 UTC, Glease approved these changes

2020-10-12 14:30 UTC, merged