Extremely Ultimate Capacitor
GTNewHorizons/KekzTech pull request #57
Opened 2023-02-04 23:33 UTC by GDCloudstrike

Adds the Extremely Ultimate Capacitor, also known as the UEV capacitor.
It has the same EU capacity as the Ultimate Capacitor, but has 100x wireless power throughput capabilities (1 Trillion eu/t).
For that reason it also has 100x passive loss (100M eu/t). 
The power requirements in endgame are reaching trillions of eu/t which wireless power can't reasonable handle with the 10 beu/t transfer capacity limit of UHV capacitors.
The UEV capacitor aims to resolve that issue and allow players to use their power stored in the wireless network to the fullest.

Its recipe follows the trend of the lapotronic batteries, but with higher tier materials and parts.
![image](https://user-images.githubusercontent.com/93287602/216793903-8f9ced19-6cd8-4447-b518-1e3fe1a3928a.png)

2023-02-05 08:04 UTC, BlueWeabo requested changes

2023-02-05 08:04 UTC, BlueWeabo commented on src/main/java/common/Recipes.java
> +                6_400_000);
use TierEU.RECIPE_UEV/UIV

2023-02-05 08:04 UTC, BlueWeabo commented on src/main/java/common/Recipes.java
> +                BW_Util.getMachineVoltageFromTier(9));
TierEU.RECIPE_UHV

2023-02-05 08:04 UTC, BlueWeabo commented on src/main/java/common/Recipes.java
> +                32);
why exactly 32 eu/t :concern: fix the others too with TierEU.RECIPE_LV

2023-02-06 03:59 UTC, BlueWeabo commented
Apply spotless and i will approve

2023-02-06 04:02 UTC, GDCloudstrike commented
> Apply spotless and i will approve
That's the thing, it doesn't work 😭

2023-02-06 04:06 UTC, BlueWeabo commented
:concern:

2023-02-06 04:06 UTC, BlueWeabo commented
well yeah i just tried it. and nope. uhhh

2023-02-06 04:08 UTC, BlueWeabo approved these changes
welp. its smt internal on rfg. not my problem XD

2023-02-06 06:08 UTC, merged