Fix space in gas turbine tooltip
GTNewHorizons/KekzTech pull request #61
Opened 2023-03-13 21:42 UTC by the-emerald

![image](https://user-images.githubusercontent.com/12746683/224838646-91819f64-caa1-4cde-8569-7985aea47b78.png)

2023-03-13 21:46 UTC, Connor-Colenso requested changes
Can we get a formatNumbers around those values while here?

2023-03-13 21:50 UTC, the-emerald commented
I'll be honest I have no clue how to do that, I just know enough to find the string and add a space 😛 - searched around the repo, couldn't find a function called `formatNumbers`.

2023-03-14 02:40 UTC, miozune commented
it's at `GT_Utility.formatNumbers`

2023-03-18 20:04 UTC, Dream-Master commented
@Connor-Colenso can you help here ?

2023-03-18 20:08 UTC, Connor-Colenso requested changes

2023-03-18 20:08 UTC, Connor-Colenso commented on src/main/java/common/tileentities/GTMTE_SOFuelCellMK1.java
> +                        "Consumes up to " + (EU_PER_TICK * 20)
GT_Utility.formatNumber(EU_PER_TICK * 20)

2023-03-18 20:08 UTC, Connor-Colenso commented on src/main/java/common/tileentities/GTMTE_SOFuelCellMK2.java
> +                        "Consumes up to " + (EU_PER_TICK * 20)
GT_Utility.formatNumber(EU_PER_TICK * 20)

2023-03-19 09:36 UTC, Dream-Master commented
@the-emerald your turn now

2023-03-19 11:09 UTC, Glease approved these changes
seems ok

2023-03-19 11:09 UTC, merged